#! /bin/bash

CONTAINER_NAME='graphite'

docker kill $CONTAINER_NAME
docker rm $CONTAINER_NAME

docker run -d -P -p 8125:8125/udp -p 25826:25826/udp -h $CONTAINER_NAME --name $CONTAINER_NAME graphite-image 
