#! /bin/bash

CONTAINER_NAME='graphite'

docker kill $CONTAINER_NAME
docker rm $CONTAINER_NAME

docker run -d -p 80:80 -p 8125:8125/udp -p 2003:2003 -p 25827:25827 -h $CONTAINER_NAME --name $CONTAINER_NAME graphite-image 
